### ISSUE TITLE
TypeError: 'LabelSetView' object is not callable

### ISSUE THREAD

**Issue by bradleyDean** [merqurio/neo4jupyter#13]
I thought this was solved, but it does not actually seem to be. 
Is there a chance that a newer version of py2neo has a breaking change?

It seems to have something to do with the labels attribute. In fact... the query in neo4jupyter.py does not seem to be actually returning any objects (not sure the proper terminology here):

![image](https://user-images.githubusercontent.com/10867313/78417177-7a1dfb80-75e4-11ea-8d1a-7ded34af198f.png)

**Comment by praneethms** [comment]
Hi ,
I used the fix that was provided and was able to get it working.  I am assuming that you are calling the draw function.
Anyways, we have a pull request with a couple of more fixes. You might want to take a look at it [here](https://github.com/merqurio/neo4jupyter/pull/11) 

For me draw and draw_subgraph were functioning with those fixes. Link [here](https://github.com/praneethms/neo4jupyter)

**Comment by merqurio** [comment]
I just merged it @praneethms , I'll push a new version. Didn't have the time to review it thoroughly. 
Thanks a lot !! If you have the time to help me maintain the library, happy to get more people involved.

**Comment by merqurio** [comment]
New version is out:
https://pypi.org/project/neo4jupyter/#history

**Comment by praneethms** [comment]
> I just merged it @praneethms , I'll push a new version. Didn't have the time to review it thoroughly.
> Thanks a lot !! If you have the time to help me maintain the library, happy to get more people involved.

No worries. 
Thanks for this Gabi.
