### ISSUE TITLE
Suggestion for handling subgraphs

### ISSUE THREAD

**Issue by osunderdog** [merqurio/neo4jupyter#3]
I have need of presenting a subgraph (py2neo.Subgraph) and this package is close to what I would like to do.  (thank you for publishing it on github)  Have code to enhance to present subgraph in cases where you want to show what will be merged or want to select a subset of nodes out of a graph for presentation.  Are you interested in taking new pull requests?  (i'm new to that process, but thought I would give it a go if you're interested.)

![screen shot 2018-04-20 at 21 30 39](https://user-images.githubusercontent.com/5431447/39079100-33f23912-44e2-11e8-865f-4a9d2f100761.png)

Example code of proposed function draw_subgraph

```python
from py2neo import Graph, Node, Relationship, NodeSelector, Subgraph, remote
import neo4jupyter
import vis
neo4jupyter.init_notebook_mode()
class Knows(Relationship): pass
class Dates(Relationship): pass
class Despises(Relationship): pass
class Person(Node): pass
sam = Node('Person', Name = 'Sam')
bob = Node('Person', Name = 'Bob')
george = Node('Person', Name = 'George')
suzy = Node('Person', Name = 'Suzy')

sg = Knows(bob, sam)
sg |= Knows(sam, suzy) 
sg |= Dates(bob, suzy)
sg |= Despises(george, bob)
neo4jupyter.draw_subgraph(sg, options = {"Person": "Name"})`
```

**Comment by merqurio** [comment]
Sure @osunderdog !! Start a pull request and I'll do my best to help you during the process 😀

**Comment by osunderdog** [comment]
pull request done

**Comment by praneethms** [comment]
Hi,
I am trying to display a sub-graph after running a cypher query using the output of  run method in the graph.

subg = graph.run(query).to_subgraph()
neo4jupyter.draw_subgraph(subg). 
Had to modify couple of lines to actually get the draw_subgraph working. Here are the modifications done to draw_subgraph definition
```
nodes = [get_vis_node_info(n,options) for n in subgraph.nodes]
edges = [get_vis_edge_info(r) for r in subgraph.relationships]

```    

However, I am unable to get the replationships displayed. Would you be able to help with this?

Regards,
Praneeth

**Comment by tejaswinihbhat** [comment]
Hi I am not able to get the subgraph with the link between the nodes. Can any help? Only nodes are displayed

**Comment by victorchenberkeley** [comment]
I try to visualize the subgraph, but returned an error. How did you do that?

query = """
MATCH (person:Person)-[:LIKES]->(drink:Drink)
RETURN person.name AS name, drink.name AS drink
"""

data = graph.run(query).to_subgraph()

neo4jupyter.draw_subgraph(data, {"Person": "name"})

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7728/2328372667.py in <module>
----> 1 neo4jupyter.draw_subgraph(data)

TypeError: draw_subgraph() missing 1 required positional argument: 'options'
