### ISSUE TITLE
TypeError: 'LabelSetView' object is not callable

### ISSUE THREAD

**Issue by profversaggi** [merqurio/neo4jupyter#5]
I get this error when running the code against a Neo4j 3.4.0 db and V4.X of Py2Neo Library.

It has to be a version issue, any suggestions?

**Comment by merqurio** [comment]
It seems to be, there is a pull request #6  that might solve it, i'll check it ASAP. 
Thanks for the report @profversaggi

**Comment by csmyth76** [comment]
I'm getting the same issue

**Comment by Niko-La** [comment]
Getting the same error when running the following notebook on local computer.

https://nicolewhite.github.io/neo4j-jupyter/hello-world.html

@inferinc are you able to run your notebook ?  I am using jupyter lab

**Comment by EvaArevalo** [comment]
I'm getting the same issue.

**Comment by loiner** [comment]
Has there been any update on this? I'm getting the same issue here as well. (Great tool btw.)

**Comment by almereyda** [comment]
@Niko-La Please note that the `neo4j-jupyter` project that you link above is different from this one. Please find its sources at https://github.com/nicolewhite/neo4j-jupyter

**Comment by ahseena96** [comment]
> Getting the same error when running the following notebook on local computer.
> 
> https://nicolewhite.github.io/neo4j-jupyter/hello-world.html
> 
> @inferinc are you able to run your notebook ? I am using jupyter lab

Getting the same issue. Any updates on this?

**Comment by merqurio** [comment]
Oh ! completely forgot about this issue, I'll check it ASAP thanks for the ping @ahseena96

**Comment by alvarolloret** [comment]
still getting the error in V5

**Comment by JimmyFengCJY** [comment]
got this error too。and in my case, i encountered this problem when t tried to parsing the data from neo4j, finally i found out that it was caused by the DataType . e.g. {'key': hello} supposed to be {'key': 'hello'}, the DataType of the value should be str,but when the raw data from neo4j is XX。So i did a DataType transform and fix it
